### ISSUE TITLE
error while running dkms autoinstall on kali linux

### ISSUE THREAD

**Issue by Cyb0rgCode** [hacklian/lenovo_82yu_i8042-dkms#1]
sudo dkms autoinstall    
The kernel is be built without module signing facility, modules won't be signed

Building module:
Cleaning build area...
make -j2 KERNELRELEASE=6.5.0-kali3-amd64 -C /lib/modules/6.5.0-kali3-amd64/build M=/var/lib/dkms/lenovo-82yu-i8042/1.0-6.5/build...
Error!  Build of i8042.ko failed for: 6.5.0-kali3-amd64 (x86_64)
Make sure the name of the generated module is correct and at the root of the
build directory, or consult make.log in the build directory
/var/lib/dkms/lenovo-82yu-i8042/1.0-6.5/build for more information.
dkms autoinstall on 6.5.0-kali3-amd64/x86_64 succeeded for lenovo-82yu-i2c-hid
dkms autoinstall on 6.5.0-kali3-amd64/x86_64 failed for lenovo-82yu-i8042(7)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.

**Comment by hacklian** [comment]
Hi,

Maybe Kali Linux is adding its own kernel patches to the driver, making this module incompatible. Searching on Google did not provide any helpful information for me. Did you try another kernel version?

I have not tried the module with Kali Linux but I'll try to take a look at it sometime in the future. If you get it working in the meantime, feel free to open a pull request for documentation updates.

**Comment by hacklian** [comment]
[Maybe this can help](https://www.kernel.org/doc/html/v4.14/admin-guide/module-signing.html)

Can you check whether or not `CONFIG_MODULE_SIG_FORCE` is enabled for your kernel?

**Comment by hacklian** [comment]
This dynamic kernel module is now obsolete as of Linux Kernel versions `>=6.5.10` and `>=6.6.1`. It is strongly recommended to update your Linux kernel to at least these versions. Following this update, the keyboard and touchpad functionalities for Lenovo V15 G4 AMN notebooks should work without the need for additional patches.
